version: '2.1'
services:
  mongodb:
    image: 'bitnami/mongodb:4.4'
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/opt/mongodb
    networks:
      mender:
        aliases:
          - mender-mongo

  nats:
      image: nats:2.6.5-alpine3.14
      command: -js -sd /opt/nats
      ports:
        - "4222:4222"
      volumes:
        - ./data/nats:/opt/nats
      networks:
        mender:
          aliases:
            - mender-nats

  workflows-worker:
    build: .
    image: mendersoftware/workflows:master
    command: worker --automigrate
    networks:
      mender:
        aliases:
          - workflows-worker

  workflows-server:
    build: .
    image: mendersoftware/workflows:master
    command: server --automigrate
    ports:
      - "8080:8080"
    networks:
      mender:
        aliases:
          - workflows-server

networks:
    mender:
