version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /frontend
    open-pull-requests-limit: 20
    package-ecosystem: npm
    schedule:
      interval: monthly
    groups:
      development-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
        exclude-patterns:
          - "@emotion*"
          - "@mui*"
      mui:
        patterns:
          - "@emotion*"
          - "@mui*"
    reviewers:
      - "mendersoftware/frontend-dependabot-reviewers"
  - commit-message:
      prefix: chore
    directory: /frontend
    package-ecosystem: docker
    schedule:
      interval: monthly
  - commit-message:
      prefix: chore
    directory: /frontend/tests/e2e_tests
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: monthly
    groups:
      playwright:
        patterns:
          - "@playwright*"
          - "playwright*"
      e2e-test-dependencies:
        dependency-type: development
        exclude-patterns:
          - "@playwright*"
          - "playwright*"
    reviewers:
      - "mendersoftware/frontend-dependabot-reviewers"
