http:
  middlewares:
    sec-headers:
      headers:
        stsSeconds: 31536000
        forceSTSHeader: true
        stsPreload: true
        stsIncludeSubdomains: true
        contentTypeNosniff: true
        browserXssFilter: true
        customRequestHeaders:
          "X-Forwarded-Proto": "https"
  
    compression:
      compress: true
  
    devauth:
      forwardAuth:
        address: "http://device-auth:8080/api/internal/v1/devauth/tokens/verify"
        authResponseHeaders: "X-MEN-RequestID"
  
    userauth:
      forwardAuth:
        address: "http://useradm:8080/api/internal/v1/useradm/auth/verify"
        authResponseHeaders: "X-MEN-RequestID,X-MEN-RBAC-Inventory-Groups,X-MEN-RBAC-Deployments-Groups,X-MEN-RBAC-Releases-Tags"
  
    json-error-responder:
      errors:
        service: error-responder@docker
        query: "/{status}.json"
        status: "401-404,408,429,500-504"
  
    inventoryV1-replacepathregex:
      replacepathregex:
        regex: "^/api/devices/v1/inventory/(.*)"
        replacement: "/api/0.1.0/attributes"
  
    inventoryMgmtV1-replacepathregex:
      replacepathregex:
        regex: "^/api/management/v1/inventory/(.*)"
        replacement: "/api/0.1.0/$1"

    mgmtStack:
      chain:
        middlewares:
          - userauth
          - sec-headers
          - compression
          - json-error-responder

    devStack:
      chain:
        middlewares:
          - devauth
          - compression
